ETicaretWeb/Models/Urunler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Sepet = new HashSet<Sepet>();
            this.SiparisKalem = new HashSet<SiparisKalem>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> RefKategoriID { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<int> UrunFiyat { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisKalem> SiparisKalem { get; set; }
    }
}

ETicaretWeb/Controllers/UrunlersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ETicaretWeb.Models;

namespace ETicaretWeb.Controllers
{
    
    public class UrunlersController : Controller
    {
        private ETicaretWebEntities db = new ETicaretWebEntities();

        // GET: Urunlers
        public ActionResult Index()
        {
            var urunler = db.Urunler.Include(u => u.Kategori);
            return View(urunler.ToList());
        }

        // GET: Urunlers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunler.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // GET: Urunlers/Create
        public ActionResult Create()
        {
            ViewBag.RefKategoriID = new SelectList(db.Kategori, "KategoriId", "KategoriAdi");
            return View();
        }

        // POST: Urunlers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UrunId,UrunAdi,RefKategoriID,UrunAciklama,UrunFiyat")] Urunler urunler,HttpPostedFileBase UrunResim)
        {
            if (ModelState.IsValid)
            {
                db.Urunler.Add(urunler);
                db.SaveChanges();
                if(UrunResim!=null && UrunResim.ContentLength>0)
                {
                    string filepath = Path.Combine(Server.MapPath("~/Resim"),urunler.UrunId + ".jpg");
                    UrunResim.SaveAs(filepath);
                }
                return RedirectToAction("Index");
            }

            ViewBag.RefKategoriID = new SelectList(db.Kategori, "KategoriId", "KategoriAdi", urunler.RefKategoriID);
            return View(urunler);
        }

        // GET: Urunlers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunler.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            ViewBag.RefKategoriID = new SelectList(db.Kategori, "KategoriId", "KategoriAdi", urunler.RefKategoriID);
            return View(urunler);
        }

        // POST: Urunlers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UrunId,UrunAdi,RefKategoriID,UrunAciklama,UrunFiyat")] Urunler urunler,HttpPostedFileBase UrunResim)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urunler).State = EntityState.Modified;
                db.SaveChanges();
                if (UrunResim != null && UrunResim.ContentLength > 0)
                {
                    string filepath = Path.Combine(Server.MapPath("~/Resim"), urunler.UrunId + ".jpg");
                    UrunResim.SaveAs(filepath);
                }
                return RedirectToAction("Index");
            }
            ViewBag.RefKategoriID = new SelectList(db.Kategori, "KategoriId", "KategoriAdi", urunler.RefKategoriID);
            return View(urunler);
        }

        // GET: Urunlers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunler.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // POST: Urunlers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urunler urunler = db.Urunler.Find(id);
            db.Urunler.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ETicaretWeb/Views/Urunlers/Create.cshtml
@model ETicaretWeb.Models.Urunler

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Urunlers", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Urunler</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RefKategoriID, "RefKategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("RefKategoriID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RefKategoriID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunAciklama, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunAciklama, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunAciklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunFiyat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunFiyat, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
       <label class="control-label col-md-2">Urun Resim</label>
        <div class="col-md-10">
            <input type="file" id="UrunResim" name="UrunResim" class="form-control" />
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ETicaretWeb/Views/Urunlers/Delete.cshtml
@model ETicaretWeb.Models.Urunler

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Urunler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunAciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunFiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ETicaretWeb/Views/Urunlers/Details.cshtml
@model ETicaretWeb.Models.Urunler

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Urunler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunAciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunFiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UrunId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ETicaretWeb/Views/Urunlers/Edit.cshtml
@model ETicaretWeb.Models.Urunler

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Urunlers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Urunler</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UrunId)

    <div class="form-group">
        @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RefKategoriID, "RefKategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("RefKategoriID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RefKategoriID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunAciklama, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunAciklama, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunAciklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UrunFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunFiyat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunFiyat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Urun Resim</label>
        <div class="col-md-10">
            <input type="file" id="UrunResim" name="UrunResim" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ETicaretWeb/Views/Urunlers/Index.cshtml
@model IEnumerable<ETicaretWeb.Models.Urunler>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </th>

        <th>
            Resim
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrunAciklama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrunFiyat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UrunAdi)
        </td>

        <td>
            <img src="~/Resim/@(item.UrunId).jpg" width="100"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrunAciklama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrunFiyat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UrunId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UrunId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UrunId })
        </td>
    </tr>
}

</table>