ETicaretWeb/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ETicaretWeb.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Net;

namespace ETicaretWeb.Controllers
{
    public class SepetController : Controller
    {
        ETicaretWebEntities db = new ETicaretWebEntities();
        // GET: Sepet
        public ActionResult Index()
        {
            var sepet = db.Sepet.Include(s => s.Urunler);
            return View(sepet.ToList());
        }

        public ActionResult SepeteEkle(int? adet,int id)
        {
            string userId = User.Identity.GetUserId();
            Sepet s = db.Sepet.FirstOrDefault(a => a.RefAspNetUserId == userId && a.RefUrunId == id);
            Urunler u = db.Urunler.Find(id);

            if(s==null)
            {
                Sepet yeniurun = new Sepet()
                {
                    RefAspNetUserId = userId,
                    RefUrunId=id,
                    Adet=adet ?? 1,
                    Tutar=(adet ?? 1) * u.UrunFiyat
                };
                db.Sepet.Add(yeniurun);
            }
            else
            {
                s.Adet = s.Adet + (adet ?? 1);
                s.Tutar = s.Adet * u.UrunFiyat;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult SepetGuncelle(int? adet, int? id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sepet sepet = db.Sepet.Find(id);
            if(sepet==null)
            {
                return HttpNotFound();
            }

            Urunler urun = db.Urunler.Find(sepet.RefUrunId);
            sepet.Adet = adet ?? 1;
            sepet.Tutar = sepet.Adet * urun.UrunFiyat;

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            Sepet sepet = db.Sepet.Find(id);
            db.Sepet.Remove(sepet);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ETicaretWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div style="background:rgba(0, 0, 0, 0.70)" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AnaSayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kategoriler", "Index", "Kategoris")</li>
                    <li>@Html.ActionLink("Urunler", "Index", "Urunlers")</li>
                    <li>@Html.ActionLink("Sepetim", "Index", "Sepet")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ETicaretWeb</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/ckeditor/ckeditor.js")
    @RenderSection("scripts", required: false)
</body>
</html>